### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by erickok** [erickok/pastt#3]
*Original issue from https://code.google.com/p/android-php-translator/issues/detail?id=31*

*Reported by HermannMagliacane.HM, Jul 17, 2013*
Add CAPTCHA to prevent spam

**Comment by oRRs** [comment]
I've implemented this using the reCAPTCHA library from Google. This has stopped (previously daily) spam submissions on my public translation page completely for about a year now.
Hope someone finds this useful. :)

**Comment by erickok** [comment]
Merged, thanks! Note for future users, you can get your Google reCAPTHA code at https://www.google.com/recaptcha/admin
